source("createOriginalMA1.R")
source("createOriginalMA1Replicated.R")
source("exportOriginal.R")
source("createCMatrix.R")
source("createDMatrix.R")
source("createProductCol.R")
source("createProductColReplicated.R")
source("saveProductCol.R")
source("drawProductCol.R")
source("createAcf.R")
source("drawAcf.R")
source("createPacf.R")
source("drawPacf.R")
source("createBetaArray.R")
source("createBetaArrayReplicated.R")
source("createCHatMatrix.R")
source("createDHatMatrix.R")
source("createDiffCMatrix_vs_CHatMatrix.R")
source("createDiffDMatrix_vs_DHatMatrix.R")
source("drawCvsCHat.R")
source("drawDvsDHat.R")
source("createLRVof2dArray.R")
source("createLRVof3dArray.R")


